//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camp
    {
        public int campID { get; set; }
        public string campName { get; set; }
        public string campDate { get; set; }
        public string campLocation { get; set; }
    }
}
