//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int donationID { get; set; }
        public int donorID { get; set; }
        public string donationDate { get; set; }
    
        public virtual donor donor { get; set; }
    }
}
