//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receiver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receiver()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int receiverID { get; set; }
        public string receiverName { get; set; }
        public string receiverDOB { get; set; }
        public string receiverPhone { get; set; }
        public string receiverGender { get; set; }
        public int donorID { get; set; }
    
        public virtual donor donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
