//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int reportID { get; set; }
        public int donorID { get; set; }
        public string bloodGroup { get; set; }
        public string hmgLvl { get; set; }
        public string bsLvl { get; set; }
        public string rbc { get; set; }
        public string wbc { get; set; }
        public string reportDate { get; set; }
    
        public virtual donor donor { get; set; }
    }
}
