//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public int shipmentID { get; set; }
        public int branchID { get; set; }
        public int bloodAmount { get; set; }
        public string shipDate { get; set; }
    
        public virtual branch branch { get; set; }
    }
}
